"""criando tabelas

Revision ID: 4d90009c4d17
Revises: 7ba17f85eff6
Create Date: 2025-08-28 22:28:36.840662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d90009c4d17'
down_revision = '7ba17f85eff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendas',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('valor_total', sa.Float(precision=10), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id_produto'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.drop_table('pedidos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_produto', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_pedido', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('valor_total', sa.REAL(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name=op.f('pedidos_id_cliente_fkey')),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id_produto'], name=op.f('pedidos_id_produto_fkey')),
    sa.PrimaryKeyConstraint('id_pedido', name=op.f('pedidos_pkey'))
    )
    op.drop_table('vendas')
    # ### end Alembic commands ###
