"""add quantidade to vendas

Revision ID: a1fc89ae71b0
Revises: 4d90009c4d17
Create Date: 2025-08-28 22:48:59.561907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1fc89ae71b0'
down_revision = '4d90009c4d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade', sa.Integer(), nullable=False))
        batch_op.alter_column('valor_total',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.alter_column('valor_total',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('quantidade')

    # ### end Alembic commands ###
